format = "$shlvl$shell$username$hostname$directory$nix_shell$git_branch$git_commit$git_state$git_status$python$env_var$jobs$cmd_duration\n$character"
add_newline = true

[directory]
truncation_length = 4
truncation_symbol = 'â€¦/'
truncate_to_repo = false
style = 'cyan'

[git_branch]
# symbol = 'ğŸŒ± '
# truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']


[git_status]
conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
staged = '[++\($count\)](green)'
# renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[hostname]
ssh_only = false
ssh_symbol = 'ğŸŒ '
# format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
format = '[$hostname](green) [$ssh_symbol](bold blue):'
# trim_at = '.companyname.com'
disabled = false

[python]
symbol = 'ğŸ'
style = 'yellow'
pyenv_version_name = true
format = ' [${symbol}(\($virtualenv\) )]($style)'
detect_extensions = ["py"]
detect_files = [
    "requirements.txt",
    ".python-version",
    "pyproject.toml",
    "Pipfile",
    "tox.ini",
    "setup.py",
    "__init__.py",
]
detect_folders = []

[rust]
format = '[$symbol($version )]($style)'
# [rust]
# format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "ğŸ¦€"
style = "bold red"
disabled = false
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]
detect_folders = []


# [status]
# style = 'bg:blue'
# symbol = 'ğŸ”´'
# success_symbol = 'ğŸŸ¢'
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
# map_symbol = true
# disabled = false

[username]
style_user = 'white'
style_root = 'black bold'
format = '[$user]($style)[@](bold gray)'
disabled = false
show_always = true

[cmd_duration]
min_time = 500
format = '[$duration](bold gray)'
